//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.14 at 01:39:19 PM NZST 
//


package nz.co.iswe.generator.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for GeneratorConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneratorConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="input" type="{http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0}InputConfig" minOccurs="0"/>
 *         &lt;element name="output" type="{http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0}OutputConfig" minOccurs="0"/>
 *         &lt;element name="helpers" type="{http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0}ReferenceHelpers" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0}ListOfProperties" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneratorConfig", propOrder = {

})
public class GeneratorConfig {

    protected InputConfig input;
    protected OutputConfig output;
    protected ReferenceHelpers helpers;
    protected ListOfProperties properties;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "class")
    protected String clazz;

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link InputConfig }
     *     
     */
    public InputConfig getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputConfig }
     *     
     */
    public void setInput(InputConfig value) {
        this.input = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link OutputConfig }
     *     
     */
    public OutputConfig getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputConfig }
     *     
     */
    public void setOutput(OutputConfig value) {
        this.output = value;
    }

    /**
     * Gets the value of the helpers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceHelpers }
     *     
     */
    public ReferenceHelpers getHelpers() {
        return helpers;
    }

    /**
     * Sets the value of the helpers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceHelpers }
     *     
     */
    public void setHelpers(ReferenceHelpers value) {
        this.helpers = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfProperties }
     *     
     */
    public ListOfProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfProperties }
     *     
     */
    public void setProperties(ListOfProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

}
