//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.14 at 01:39:19 PM NZST 
//


package nz.co.iswe.generator.config.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nz.co.iswe.generator.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IsweGenerators_QNAME = new QName("http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0", "iswe-generators");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nz.co.iswe.generator.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneratorContextConfig }
     * 
     */
    public GeneratorContextConfig createGeneratorContextConfig() {
        return new GeneratorContextConfig();
    }

    /**
     * Create an instance of {@link ListOfHelpers }
     * 
     */
    public ListOfHelpers createListOfHelpers() {
        return new ListOfHelpers();
    }

    /**
     * Create an instance of {@link ListOfOneToOneGenerators }
     * 
     */
    public ListOfOneToOneGenerators createListOfOneToOneGenerators() {
        return new ListOfOneToOneGenerators();
    }

    /**
     * Create an instance of {@link InputConfig }
     * 
     */
    public InputConfig createInputConfig() {
        return new InputConfig();
    }

    /**
     * Create an instance of {@link GroupConfig }
     * 
     */
    public GroupConfig createGroupConfig() {
        return new GroupConfig();
    }

    /**
     * Create an instance of {@link GeneratorConfig }
     * 
     */
    public GeneratorConfig createGeneratorConfig() {
        return new GeneratorConfig();
    }

    /**
     * Create an instance of {@link ReferenceHelper }
     * 
     */
    public ReferenceHelper createReferenceHelper() {
        return new ReferenceHelper();
    }

    /**
     * Create an instance of {@link OutputConfig }
     * 
     */
    public OutputConfig createOutputConfig() {
        return new OutputConfig();
    }

    /**
     * Create an instance of {@link ListOfManyToOneGenerators }
     * 
     */
    public ListOfManyToOneGenerators createListOfManyToOneGenerators() {
        return new ListOfManyToOneGenerators();
    }

    /**
     * Create an instance of {@link HelperConfig }
     * 
     */
    public HelperConfig createHelperConfig() {
        return new HelperConfig();
    }

    /**
     * Create an instance of {@link ListOfGroups }
     * 
     */
    public ListOfGroups createListOfGroups() {
        return new ListOfGroups();
    }

    /**
     * Create an instance of {@link ReferenceGenerator }
     * 
     */
    public ReferenceGenerator createReferenceGenerator() {
        return new ReferenceGenerator();
    }

    /**
     * Create an instance of {@link ReferenceHelpers }
     * 
     */
    public ReferenceHelpers createReferenceHelpers() {
        return new ReferenceHelpers();
    }

    /**
     * Create an instance of {@link ListOfProperties }
     * 
     */
    public ListOfProperties createListOfProperties() {
        return new ListOfProperties();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneratorContextConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iswe.co.nz/isweframework/xsd/iswe-generator-1.0.0", name = "iswe-generators")
    public JAXBElement<GeneratorContextConfig> createIsweGenerators(GeneratorContextConfig value) {
        return new JAXBElement<GeneratorContextConfig>(_IsweGenerators_QNAME, GeneratorContextConfig.class, null, value);
    }

}
